from app.agents.prompts.templates import (
    COORDINATOR_PROMPT,
    JOURNEY_PLANNING_PROMPT,
    MONITORING_PROMPT,
    EMERGENCY_PROMPT,
    ASSISTANT_PROMPT
)

__all__ = [
    "COORDINATOR_PROMPT",
    "JOURNEY_PLANNING_PROMPT",
    "MONITORING_PROMPT",
    "EMERGENCY_PROMPT",
    "ASSISTANT_PROMPT"
]
