from enum import Enum

class JourneyEventType(Enum):
    GPS_UPDATE = "GPS_UPDATE"
    SOS_TRIGGERED = "SOS_TRIGGERED"
    MANUAL_REROUTE = "MANUAL_REROUTE"
    JOURNEY_PAUSED = "JOURNEY_PAUSED"
    JOURNEY_RESUMED = "JOURNEY_RESUMED"
